name: CSV Lint on CSV File Changes

on:
  push:
    paths:
      - "data/raw/**.csv"
      - ".github/workflows/lint.yml"
  pull_request:
    paths:
      - "**.py"
      - ".github/workflows/lint.yml"

jobs:
  csv-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Read access to the repository contents is enough for linting
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: csvlinter
        uses: kcheriyath/csvlinter@8f78b213da9be31ba771a516ad63235ec65fbbd0 # V0.7.1
        with:
          find_pattern: "*.csv"
          fail_on_error: "true"
          extra_params: "--lazyquotes"
