name: Update WISQARS Data

on:
  schedule:
    - cron: "0 15 * * 6" # At 15:00 UTC on Saturday (between cdc_open at 14:00 and wonder at 16:00)
  workflow_dispatch:

jobs:
  update-wisqars-data:
    runs-on: ubuntu-latest
    environment:
      name: prod
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@ae62891fec2bb8e7d6c99fc78c9fec3a63790f8d # v10.0.0
        with:
          version: "latest"

      - name: Download all WISQARS datasets
        env:
          CDC_DATA_APP_TOKEN: ${{ secrets.CDC_DATA_APP_TOKEN }}
        run: |
          uv run python -m wisqars.download

      - name: Commit and push changes
        run: |
          git status
          git config --local user.email "noreply@github.com"
          git config --local user.name "github-actions[bot]"
          git add data/raw/wisqars/
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update of WISQARS data on $(date +'%Y-%m-%d')"
            git pull --rebase origin main
            git push -u origin main
          fi
