name: Update CDC Open Data

on:
  schedule:
    - cron: "0 14 * * 6" # At 14:00 UTC on Saturday
  workflow_dispatch:

jobs:
  update-cdc-open-data:
    runs-on: ubuntu-latest
    environment:
      name: prod
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version: "latest"

      - name: Download all CDC Open datasets
        env:
          CDC_DATA_APP_TOKEN: ${{ secrets.CDC_DATA_APP_TOKEN }}
        run: |
          uv run python -m cdc_open.download

      - name: Fetch respiratory hospitalization data
        env:
          CDC_DATA_APP_TOKEN: ${{ secrets.CDC_DATA_APP_TOKEN }}
        run: |
          uv run python -m cdc_open.fetch_resp

      - name: Commit and push changes
        run: |
          git status
          git config --local user.email "noreply@github.com"
          git config --local user.name "github-actions[bot]"
          git add data/raw/cdc_open/ data/raw/resp/
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update of CDC Open Data on $(date +'%Y-%m-%d')"
            git pull --rebase origin main
            git push -u origin main
          fi
