name: Update Wonder Data

on:
  push:
    branches:
      - main
    paths:
      - "src/wonder/**.py"
      - ".github/workflows/update_wonder.yml"
  schedule:
    - cron: "0 16 * * 6" # At 16:00 on Saturday
  workflow_dispatch:

jobs:
  update-wonder-data:
    runs-on: ubuntu-latest
    environment:
      name: prod
    permissions:
      contents: write # Write access is needed to push changes back to the repository
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@ae62891fec2bb8e7d6c99fc78c9fec3a63790f8d # v10.0.0
        with:
          version: "latest"

      - name: Install Playwright browsers
        run: |
          uv run playwright install chromium --with-deps

      - name: Crawl and scan CDC WONDER website for new datasets
        continue-on-error: true # best effort, we already have most datasets
        run: |
          uv run python -m wonder.scrape.crawl
          uv run python -m wonder.scrape.scanner

      - name: Crawl CDC WONDER datasets for new query parameters
        continue-on-error: true # best effort, we can use the previous query parameters
        run: |
          uv run python -m wonder.scrape.query --range 1-250

      - name: Catalog CDC WONDER into health topics
        continue-on-error: true # best effort, we can use the previous catalog data
        run: |
          uv run python -m wonder.scrape.catalog

      - name: Commit and push changes
        if: github.ref == 'refs/heads/main'
        run: |
          git status
          git config --local user.email "noreply@github.com"
          git config --local user.name "github-actions[bot]"
          git add data/raw/wonder/
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update of CDC WONDER data, topics, and query parameters on $(date +'%Y-%m-%d')"
            git pull --rebase origin main
            git push -u origin main
          fi
